export const QueryKeys = {
  TRANSACTIONS_PAGINATED: 'TRANSACTIONS_PAGINATED',
  TRANSACTIONS_LIST_GROUPED: 'TRANSACTIONS_LIST_GROUPED',
  TRANSACTIONS: 'TRANSACTIONS',
  TRANSACTION_ITEMS: 'TRANSACTION_ITEMS',
  ITEMS_LIST: 'ITEMS_LIST'
}
